### PR TITLE
Failsafe option when galaxy config file is not in the expected place.

### PR DESCRIPTION
**Pull request by pcm32**
An old commit that I failed to PR, which sorts out issue https://github.com/bgruening/docker-galaxy-stable/issues/433 at docker-galaxy-stable.

### CODE REVIEW

**Comment by pcm32** [comment]
Hi there! I need this added to the main branch for 18.05 as well... I'm starting to use 18.05 on k8s and still seeing this issue:

```
IOError: [Errno 2] No such file or directory: '/etc/galaxy/galaxy.yml'
```

Thanks!

**Comment by pcm32** [comment]
I'm a bit troubled by this. I recently started testing 18.05 on k8s, but I keep getting some HTTP errors (welcome page doesn't show up, file uploads fail with `Warning: Not Found (404)`), and before that I was getting some red errors at the very beginning (they went away with me setting galaxy.filter-with=/galaxy, although from documentation I'm not sure that this is even correct to do). 

On one side, the dagobah training slides it state that a `galaxy.yaml` file is not needed... yet without it (and the commit on this PR), galaxy 18.05 doesn't start on the compose setup (at least on k8s, maybe I'm doing something wrong). On the other hand, using the default yaml file, as proposed here, seems to be imposing some defaults for UWSGI that I'm not sure are correct, and that I'm starting to think might be related to my http errors... 

Any comments @bgruening ?

**Comment by bgruening** [comment]
I'm not sure what is going on there. The yml should not be needed as Galaxy will fallback to the sample file. Also no configuration is done with the yaml file, everything should happen through supervisor and ENVs. I'm super confused here :(

And I have trouble to test this, as it seems to work for me with compose :(

**Comment by pcm32** [comment]
Maybe we are building the containers with slightly different flags that in one case make certain scripts try to read the yaml file?

**Comment by pcm32** [comment]
My http part setup is working, and looking at the default yaml setup there is no much there, so I presume that this is not affecting that part.

**Comment by pcm32** [comment]
I see this again on 18.09 with a completely clean installation.... complete error is:

```
Waiting for database
Traceback (most recent call last):
  File "/usr/local/bin/check_database.py", line 18, in <module>
    db_url = get_config(sys.argv)['db_url']
  File "/export/galaxy-central/lib/galaxy/model/orm/scripts.py", line 126, in get_config
    properties = load_app_properties(config_file=config_file, config_prefix=config_override, config_section=config_section)
  File "/export/galaxy-central/lib/galaxy/util/properties.py", line 91, in load_app_properties
    with open(config_file, "r") as f:
IOError: [Errno 2] No such file or directory: '/etc/galaxy/galaxy.yml'
```

**Comment by pcm32** [comment]
This has been merged by some other PR, as changes are there already:

https://github.com/galaxyproject/ansible-galaxy-extras/commit/934af939d4baf208fbed8edeafee40a06a47fe78#diff-205c98235541487412061d12953dc4c0

will close then this PR.

**Pull request closed without merging**
