### PR TITLE
Feature/isatools-lite installation

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds an isatools-lite optional install managed by ansible to support the functionality of the isa-tab and isa-json composite datatypes recently contributed by PhenoMeNal. This will be executed in the compose galaxy-init container provided that a build argument `--build-arg ISATOOLS_LITE_INSTALL=True` is given on docker build.

It also pins uwsgi to version 2.0.15 as a new version 2.0.16 came for which there is no wheel, producing failures when building containers.

### CODE REVIEW

**Comment by jmchilton** [comment]
How are you installing the datatypes in Galaxy - are you pointing at a fork of Galaxy with the datatypes? If yes, can't you just add these to that Galaxy's requirements file so these are picked automatically?

**Comment by pcm32** [comment]
Hi! The main issue I have is that isatools is very heavy by default on dependencies, but these dependencies are not really needed for the datatype, so we need to install without dependencies to avoid bloating stuff. But I see your point of course that this should be installed as all other Galaxy deps in the Galaxy requirements. Can you add entries into `requirements.txt` that avoid following dependencies? We are talking about ~400 MB of added dependencies. 

I expect this to be a transition installation mode, as we are working with colleagues in generating a branch of ISA that can be installed with less trouble.

**Comment by pcm32** [comment]
Saw some unexpected issues... let me set this to WIP for a little while.

**Comment by pcm32** [comment]
This effort is irrelevant since the ansible call used by kn makes use of netifaces on runtime.

**Comment by pcm32** [comment]
Sorry, closed wrong PR!

**Comment by bgruening** [comment]
Thanks @pcm32 for working on this!

**Comment by pcm32** [comment]
Hi think I should be able to avoid this whole non-dependency installation soon. Maybe I'll open another PR just for pinning uwsgi

**Comment by abretaud** [comment]
> Maybe I'll open another PR just for pinning uwsgi

@pcm32 if you have time, yes, it'd be great ! I need it too to fix docker image building

**Comment by pcm32** [comment]
@abretaud please see PR #190 which only includes that change, hopefully it will be merged straight away by @bgruening or other admin.

**Comment by abretaud** [comment]
Coooool, thanks @pcm32!

**Comment by pcm32** [comment]
I have added now a PR at starforge to get the minimal ISA-tools that we are using installed:
https://github.com/galaxyproject/starforge/pull/197

That would make this PR unnecessary :-) - or simplify it a lot.

**Comment by pcm32** [comment]
I don't think that this is needed any longer....

**Pull request closed without merging**
