### PR TITLE
Set galaxy_uwsgi_static_conf to false by default.

### PR DESCRIPTION
**Pull request by mvdbeek**
set PYTHONHOME to galaxy_venv_dir.

### CODE REVIEW

**Comment by bgruening** [comment]
This one is a must `galaxy_uwsgi_static_conf: false` and an important bugfix.
I guess the `PYTHONHOME` does not hurt, I'm just wondering why this is needed.

**Comment by mvdbeek** [comment]
I'm not quite sure either why PYTHONHOME is needed, but when running eggless galaxy all imports are failing. Normally this is supposed to be taken care of when you call the python within the virtualenv ... .

**Comment by bgruening** [comment]
With eggless you mean Galaxy on wheels :)?
Can we try to fix this upstream? @natefoo can probably enlighten us here.
Do you mind to create a separate PR for the bugfix?

**Comment by mvdbeek** [comment]
Sure, no problem.

**Comment by mvdbeek** [comment]
closing this in favor of PR #35 and raising an issue for the PYTHONHOME problem.

**Comment by natefoo** [comment]
We use `PYTHONHOME` (actually, `--virtualenv`, which is an alias for the option version of that var) for the tool shed as well since uWSGI is installed via apt on that system. If uwsgi is installed in Galaxy's virtualenv, the option is not necessary.

[Related change](https://github.com/galaxyproject/usegalaxy-playbook/commit/b4841230c39de5e87136d371a9a7366b8055689d)

**Comment by mvdbeek** [comment]
thanks @natefoo, this is still weird then. Here we're already using `{{ galaxy_venv_dir }}/bin/uwsgi`, yet somehow we seem to need to set `PYTHONHOME`. @bgruening should we also use `--virtualenv` ?

**Comment by mvdbeek** [comment]
This is superceded by PR #35 and PR #36

**Pull request closed without merging**
