### PR TITLE
Welcome page fix

### PR DESCRIPTION
**Pull request by bgruening**
This should fix https://github.com/bgruening/docker-galaxy-stable/issues/48

### CODE REVIEW

**Comment by jmchilton** [comment]
I will admit to not understanding the fix really - but is that exposing that whole directory? You probably don't want to do that right since it might have for instance a ``master_api_key`` in the galaxy.ini file. 

If this solution works - it seems like you could create an ``/etc/galaxy/web`` maybe and change the value in the init file and alias to ``/etc/galaxy/web``.

**Comment by bgruening** [comment]
I was not able to get `/etc/galaxy` listed. But better save than sorry. Thanks for the hint.

**Comment by bgruening** [comment]
@jmchilton do you think this is ok now?

**Comment by jmchilton** [comment]
Sure - thanks for making that change. Does the initial startup script need to be modified also?

**Pull request merged**
