### PR TITLE
checking for a running pg instance

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by mvdbeek** [comment]
It's not the exact same thing, but would [pg_isready](https://www.postgresql.org/docs/9.3/static/app-pg-isready.html) work instead of the custom script ?

**Comment by bgruening** [comment]
Yes we could, but I was not sure if we can assume >=9.3, can we?

**Comment by bgruening** [comment]
@mvdbeek have you seen my last comment? Are you ok with this PR?

**Comment by mvdbeek** [comment]
Sure, no problem.

**Pull request merged**
