### PR TITLE
If rel-dest and rel-src are the same ...

### PR DESCRIPTION
**Pull request by bgruening**
we do no need to move and symlink again.

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek @jmchilton can I have a review please?

**Comment by jmchilton** [comment]
So much testing - absolutely lovely :100:!

**Comment by bgruening** [comment]
Thanks that was fast!

**Comment by jmchilton** [comment]
I was reviewing it as you requested the review :laughing:.

**Comment by bgruening** [comment]
:heart_eyes:

**Pull request merged**
