### PR TITLE
Made install_repository more generic

### PR DESCRIPTION
**Pull request by voegtlel**

### CODE REVIEW

**Comment by bgruening** [comment]
Can you target dev please.

**Comment by voegtlel** [comment]
Which dev?

**Comment by bgruening** [comment]
I see, sorry for the noise. Everything fine, looks good.

**Comment by bgruening** [comment]
I can not even see the error. I think travis is still not working as expected. Amazon had large problems yesterday and things are not fully recovered as it seems.

**Comment by bgruening** [comment]
Travis is working again, but now the `The command "make test_bioblend" exited with 0.` is failing. This PR looks good and this failure is most likely unrelated.

**Pull request merged**
