### PR TITLE
Synchronize nginx error doc handling with ansible-galaxy role.

### PR DESCRIPTION
**Pull request by jmchilton**
Probably shouldn't break anything for existing setup since I don't think docker-galaxy-stable for instance was writing anything to /root/502.html right?

xref https://github.com/galaxyproject/ansible-galaxy/commit/1bff199822c7c8456a6d2ff802ec98732c57a4d0
xref https://github.com/galaxyproject/planemo-machine/issues/85

### CODE REVIEW

**Comment by bgruening** [comment]
+1 from my site!

**Comment by bgruening** [comment]
@drosofff is this ok for you as well?

**Comment by drosofff** [comment]
Yep +1 from GalaxyKickStart

**Comment by bgruening** [comment]
Awesome, thanks for the fast response!

**Pull request merged**
