### PR TITLE
Drop egg support in tasks/slurm.yml

### PR DESCRIPTION
**Pull request by drosofff**
@mvdbeek (in response to https://github.com/galaxyproject/ansible-galaxy-extras/pull/217):

something like that ?

### CODE REVIEW

**Comment by mvdbeek** [comment]
Yes, can you also drop the `galxy_egg_cache` variable in defaults/main.yml and the fetch_eggs step in tasks/pbs.yml ?

**Comment by drosofff** [comment]
Should we address the issue of the test test failing at some point ?

**Comment by mvdbeek** [comment]
Yes, I did look into this a bit and the proper fix would be to upgrade python in the container, but #219 should have fixed the tests

**Comment by drosofff** [comment]
@mvdbeek agree, this is puzzling !!
maybe drop the the `dest=/dev/null` in `url="http://deb.nodesource.com/node/dists/{{ ansible_distribution_release }}/Release" dest=/dev/null` ? The @bgruening commit https://github.com/galaxyproject/ansible-galaxy-extras/commit/9e6bd6daa77f57dadc09ebb9bf00956248361d73 was also doing it.

**Comment by drosofff** [comment]
and now the test of this PR passes. don't get it...

**Comment by mvdbeek** [comment]
The default travis test merges the PR into master and then runs the tests on the result of the merge.

**Pull request merged**
