### PR TITLE
postgres can be configured not to autostart (NONUSE=postgres)

### PR DESCRIPTION
**Pull request by voegtlel**
To allow startup.sh not to start the postgres service, supervisor_postgres_autostart was introduced. Defaults to the same behavior as before.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Very nice, :+1:

**Comment by mvdbeek** [comment]
The failing tests are related to key fetching from the docker repo, but that's not related to this PR.
I've re-triggered it and it failed again, but that's a separate issue.

**Comment by bgruening** [comment]
:+1: for me as well!

**Comment by bgruening** [comment]
Upstream is working on a fix for failing travis: https://github.com/docker/docker/issues/16941

**Comment by bgruening** [comment]
@mvdbeek can we merge this?

**Pull request merged**
