### PR TITLE
update all scripts to handle latest Galaxy & Docker releases

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek I think we have a working version. 
Would be awesome if you can test this + the `more_travis` branch. I assume latest Docker with an backend != overlay.

**Comment by mvdbeek** [comment]
Sure, building now.

**Comment by mvdbeek** [comment]
```
galaxy.webapps.galaxy.controllers.visualization ERROR 2016-01-10 20:59:42,095 error rendering visualization (rstudio): 'Bunch' object has no attribute 'proxy_url'
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/controllers/visualization.py", line 747, in render
    return plugin.render( trans=trans, embedded=embedded, **kwargs )
  File "lib/galaxy/visualization/plugins/plugin.py", line 135, in render
    return self._render( render_vars, trans=trans, embedded=embedded )
  File "lib/galaxy/visualization/plugins/plugin.py", line 281, in _render
    return trans.fill_template( template_filename, template_lookup=self.template_lookup, **render_vars )
  File "lib/galaxy/web/framework/webapp.py", line 811, in fill_template
    return self.fill_template_mako( filename, **kwargs )
  File "lib/galaxy/web/framework/webapp.py", line 825, in fill_template_mako
    return template.render( **data )
  File "/galaxy-central/.venv/local/lib/python2.7/site-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/galaxy-central/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/galaxy-central/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/galaxy-central/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/export/galaxy-central/database/compiled_templates/rstudio.mako.py", line 62, in render_body
    notebook_pubkey_url = ie_request.url_template('${PROXY_URL}/rstudio/auth-public-key')
  File "lib/galaxy/web/base/interactive_environments.py", line 174, in url_template
    url = url_template.replace('${PROXY_URL}', str(self.attr.proxy_url)) \
AttributeError: 'Bunch' object has no attribute 'proxy_url'
```
I have seen this before ... for the records, was I supposed to set proxy_url at docker run ?

**Comment by bgruening** [comment]
No, you don't need to set anything. Do you have this file in your container under /root/cgoup... https://github.com/galaxyproject/ansible-galaxy-extras/pull/38/files#diff-3809e0a6e5e4b5beacef0e13064abde6

Does `docker info` work inside of your container?

**Comment by mvdbeek** [comment]
```
root@9e000a06d823:/galaxy-central# docker info
Containers: 0
Images: 46
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /export/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 46
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS (containerized)
CPUs: 2
Total Memory: 7.798 GiB
Name: 9e000a06d823
ID: AJLN:MRTJ:MEKR:K3OW:QLRD:ICVP:NL4F:3XIS:K5ZN:OUSQ:O66I:JCCA
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
```
root@9e000a06d823:/root# head cgroupfs_mount.sh 
#!/bin/bash
set -e

# DinD: a wrapper script which allows docker to be run inside a docker container.
# Original version by Jerome Petazzoni <jerome@docker.com>
# See the blog post: https://blog.docker.com/2013/09/docker-can-now-run-within-docker/
#
# This script should be executed inside a docker container in privilieged mode
# ('docker run --privileged', introduced in docker 0.6).
```

**Comment by mvdbeek** [comment]
This works for me now, thanks @bgruening :+1:

**Comment by bgruening** [comment]
Awesome! Thanks for testing. I will remove the WIP and wait a few hours before merging this.

**Comment by jmchilton** [comment]
Awesome sauce - you guys rock - keep up the great work!

**Pull request merged**
