### PR TITLE
Fix installation of munge package in ubuntu 16.04

### PR DESCRIPTION
**Pull request by drosofff**
by pre-uploading a munge.service config file with
```
ExecStart=/usr/sbin/munged --syslog
```
The issue is detailed in #136

### CODE REVIEW

**Comment by jmchilton** [comment]
Doesn't supervisor run munge though - or do you have that off in your settings?

**Comment by drosofff** [comment]
Supervisor run munge is On in my settings.
However, whether or not supervisor run munge, the munge package is installed by apt before in the playbook and this does not work in 16.04. it also crashes the slurm packages installation by the way (still in 16.04)

**Comment by jmchilton** [comment]
Okay - it seems to work in the Docker file planemo-machine but there we pre-install munge and slurm together. It also is working in the planemo machine VM which is 16.04 - so I don't understand - but I'll merge this and try another planemo machine build to see if it still works.

**Comment by drosofff** [comment]
Thanks !

>  It also is working in the planemo machine VM which is 16.04 - so I don't understand

Maybe the 16.04 planemo machine uses a layer with pre-built munge/slurm ?

**Comment by jmchilton** [comment]
So this does break planemo-machine https://github.com/galaxyproject/planemo-machine/pull/102.

```
TASK [galaxyprojectdotorg.galaxy-extras : Install munge system package] ********
ok: [localhost]
TASK [galaxyprojectdotorg.galaxy-extras : Restart munge service] ***************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failure 1 during daemon-reload: Failed to connect to bus: No such file or directory\n"}
```

Does this traceback to a particular ansible-galaxy-extras commit - was this working in the past for GalaxyKickStart?

**Comment by drosofff** [comment]
Mmm. Sorry about that. I can't tell whether it used to work for GalaxyKickStart, I started testing it extensively in 16.04 only few days ago. But it's true that I remember a quick shot 2 months ago that failed but not because of munge.
Look, I think that my code could still work without restarting services. I'll let you know asap.

On another note, I see in https://travis-ci.org/galaxyproject/planemo-machine/jobs/229988623#L491 that munge and slurm are not installed in the same order as in https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/tasks/slurm.yml. Maybe this matters ?

**Comment by mvdbeek** [comment]
> On another note, I see in https://travis-ci.org/galaxyproject/planemo-machine/jobs/229988623#L491 that munge and slurm are not installed in the same order as in https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/tasks/slurm.yml. Maybe this matters ?

That is ansible-galaxy-os, which we are using as well. We should probably fix it there, I already have https://github.com/galaxyproject/ansible-galaxy-os/pull/21 open, which still needs some work for debian 8. I'm wondering if it makes sense to include slurm in ansible-galaxy-os ... maybe we should make that at least conditional. I guess it makes more sense to install the package in ansible-galaxy-extras.

**Comment by drosofff** [comment]
@jmchilton in the meantime I tested the modified slurm.yml without restarting service (which was not required indeed, adding a munge.service file before apt install munge is sufficient). Let me know if the new PR passes the tests in the planemo VM

**Comment by dustin-cram** [comment]
I had this problem a while back and forgot to submit a fix - the issue is that Ubuntu insists on starting services the moment that they're apt installed, so it fails at that time.

My fix was to do a manual systemd mask (creating a symlink to /dev/null at /etc/systemd/system/munge.service) before installing munge.

I'm using GalaxyKickStart which has munge managed by supervisor, so in this case it can just remain masked.  Otherwise @drosofff's fix in https://github.com/galaxyproject/ansible-galaxy-extras/issues/136 can be applied and then unmasked.

**Comment by jmchilton** [comment]
@drosofff That did indeed fix planemo-machine - thanks!

@dustin-cram Thanks for the additional information.

**Pull request merged**
