### PR TITLE
Https via LetsEncrypt

### PR DESCRIPTION
**Pull request by zfrenchee**
Another work in progress.

### CODE REVIEW

**Comment by martenson** [comment]
this is great!

**Comment by zfrenchee** [comment]
@martenson @jmchilton How does one go about testing these?

**Comment by bgruening** [comment]
This looks great! Can you add some documentation about this?

**Comment by zfrenchee** [comment]
@bgruening I like your enthusiasm! however...
1. I haven't tested it, and it's mostly copy-pasted, so I doubt it works. How do I test it? 
2. Where would you like for me to add documentation?

**Comment by bgruening** [comment]
@zfrenchee testing is hard I think.
A few links to consider: https://docs.ansible.com/ansible/letsencrypt_module.html and look at other letsencrypt ansible tests, e.g. https://github.com/bytepark/ansible-role-letsencrypt/blob/master/.travis.yml

**Comment by zfrenchee** [comment]
@bgruening Oh my gosh I can't believe I didn't see that ansible module when i first went around looking for this! Let me revise this PR.

**Comment by zfrenchee** [comment]
So my guess is that nearly all the fields should be parameters passed along to the end user. @bgruening let me know what you think.

**Comment by zfrenchee** [comment]
Unfortunately I don't think this will work, because running the ansible role during production of @bgruening's docker image will cause the image itself to have a certificate, which when multiple people go to run it, breaks the entire idea of https, I think. I don't know these technologies too well, but I think this is a fundamental roadblock for me, since I want to use these via bjoern's image. That said, I think others will likely be able to use this, if they are the ones to run this role, rather than use it through the docker image, so i've left it here, mostly finished, for someone else to pick up, or for myself to pick up later when I have more time. In the meantime, I'm going to look into a docker-based https solution for my work.

**Comment by martenson** [comment]
@zfrenchee thank you very much for exploring this road, I still think it is great direction and that deployers would benefit from having something like this readily available when deploying Galaxy

**Comment by blankenberg** [comment]
:heart: LetsEncrypt

**Comment by bgruening** [comment]
@zfrenchee one possibility is to generate this key/certificate during statup via the startup script, that should make it unique to every instance.

**Comment by zfrenchee** [comment]
@bgruening how would I do that?

**Comment by zfrenchee** [comment]
Alright, I'm moving this work over to a PR against Bjoern's image.

**Pull request closed without merging**
