### PR TITLE
remove uwsgi restart

### PR DESCRIPTION
**Pull request by bgruening**
I don't think this is needed and I have problems if I only include a uwsgi from pip.

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton @mvdbeek any reason to keep this?

**Comment by mvdbeek** [comment]
So the idea is to disable automatic uwsgi starts if it has been installed through the package manager. This is not a problem if a) you're using docker and docker restricts automatic service starting. But in ./tasks/supervisor.yml there is this section:
```
- name: Install web related system packages
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - uwsgi
    - uwsgi-plugin-python
    - supervisor
  when: galaxy_extras_install_packages
```
Which will cause uwsgi to be installed from apt, which starts a uwsgi service on non-docker systems. If you want to remove this here you also need to remove the installation of uwsgi, or you can add an `ignore_errors: yes` on the part that causes problems, or even better add `galaxy_extras_install_packages` to the conditions for this task.

**Comment by bgruening** [comment]
@mvdbeek if this is the reason, maybe we should install both via pip to get a more recent version?

**Comment by mvdbeek** [comment]
That would be good as well, yes.

**Comment by bgruening** [comment]
I have disabled it for now and will work on the pip stuff later.

**Comment by mvdbeek** [comment]
Thanks @bgruening!

**Comment by bgruening** [comment]
Cool, thanks for the merge. Next release we will have a `s17.05` version, that is a down-scaled version of Galaxy Docker with 150MB less image size: https://quay.io/repository/bgruening/galaxy?tab=tags

**Pull request merged**
