### PR TITLE
Possible fix for nginx startup failing (#130)

### LINKED ISSUE #130: Issue with PR #127
Hi all,

the last PR https://github.com/galaxyproject/ansible-galaxy-extras/pull/127 breaks nginx restarts
in GalaxyKickStart https://github.com/ARTbio/GalaxyKickStart

```
RUNNING HANDLER [galaxyprojectdotorg.galaxy-extras : restart nginx] ************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/sbin/nginx", "-s", "reload"], "delta": "0:00:00.005885", "end": "2017-04-23 16:18:23.930299", "failed": true, "rc": 1, "start": "2017-04-23 16:18:23.924414", "stderr": "nginx: [emerg] open() \"/etc/nginx/conf.d/reports_auth.conf\" failed (2: No such file or directory) in /etc/nginx/nginx.conf:36", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
```

This may be an issue in templates/startup.sh.j2 (and the cp of reports_auth.conf.source) , I am investigating.

### PR DESCRIPTION
**Pull request by abretaud**
Not very elegant I'm afraid, but it should fix #130 hopefully.
@drosofff can you test it?

### CODE REVIEW

**Comment by drosofff** [comment]
yep, thanks. I'll do it around 5pm local time ;-)

**Comment by drosofff** [comment]
@abretaud The test with your branch fix_reports_auth  is ok 👍 
There is still a ugly warning when the handler is triggered: 

```
TASK [galaxyprojectdotorg.galaxy-extras : Setup letsencrypt-specific configuration files] ***
skipping: [localhost] => (item={u'dest': u'/etc/nginx/conf.d/letsencrypt.conf', u'src': u'nginx_letsencrypt.conf.j2', u'mode': u'u=rw,g=r,o=r'})
skipping: [localhost] => (item={u'dest': u'/etc/letsencrypt/letsencrypt.conf', u'src': u'letsencrypt.conf.j2', u'mode': u'u=rw,g=r,o=r'})
skipping: [localhost] => (item={u'dest': u'/usr/local/bin/letsencrypt_refresh.sh', u'src': u'letsencrypt_refresh.sh.j2', u'mode': u'u=rwx,g=rx,o=r'})

RUNNING HANDLER [galaxyprojectdotorg.galaxy : restart galaxy] ******************
ok: [localhost] => {
    "msg": "RESTARTER NOT IMPLEMENTED - Please restart Galaxy manually"
}

RUNNING HANDLER [galaxyprojectdotorg.galaxy : email administrator with commit id] ***
skipping: [localhost]

RUNNING HANDLER [galaxyprojectdotorg.galaxy-extras : restart nginx] ************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/sbin/nginx", "-s", "reload"], "delta": "0:00:00.013255", "end": "2017-04-24 15:50:58.346200", "failed": true, "rc": 1, "start": "2017-04-24 15:50:58.332945", "stderr": "nginx: [error] open() \"/run/nginx.pid\" failed (2: No such file or directory)", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
```
But otherwise it's goes smoothly  until the end. I did not do better with my local fix yesterday.

Thanks and see you in Rennes ?

**Comment by bgruening** [comment]
Thanks a lot @abretaud for fixing and sorry for breaking @drosofff!
Can you get your use-case into travis here, so we can test it automatically and don't break it again?

**Comment by abretaud** [comment]
Great!
Yes, see you soon in galette-saucisse-land!

**Comment by drosofff** [comment]
@bgruening our use case is in travis [here](https://github.com/ARTbio/GalaxyKickStart/blob/master/.travis.yml) that automatically tests the remote roles including galaxy-extra. We can either leave it as is, or it's probably more efficient if you pick up the appropriate code lines to add them in the .travis.yml of this repo. You are familiar with this code aren't you ;-).

**Comment by bgruening** [comment]
@drosofff :)
I will take a look! Thanks.

**Pull request merged**
