### PR TITLE
24.1 tracking branch

### PR DESCRIPTION
**Pull request by jyotipm29**
Working on the [24.1](https://github.com/bgruening/docker-galaxy-stable/pull/607) docker image.

### CODE REVIEW

**Comment by bgruening** [comment]
Lets create a new branch here. Call it 24.01 and depend on this in your other PR.

**Comment by bgruening** [comment]
I created a new branch and this could be now merged, if you like. 

I guess I would recommend to you to use this standing branch (from your fork) in your main PR and we merge this when your main PR is green.

**Comment by jyotipm29** [comment]
Sounds good, I'll do that!

**Comment by bgruening** [comment]
I will merge this, so it does not get lost, its great stuff in here.

But I guess we will archive this repo, soon.

**Pull request merged**
