### PR TITLE
pins uwsgi version to 2.0.15

### PR DESCRIPTION
**Pull request by pcm32**
Sorts failing build of dockerfile on compose setup.

### CODE REVIEW

**Comment by bgruening** [comment]
I'm not sure why, but it can not find the uwsgi package or tries to get it from pypi :(

**Comment by pcm32** [comment]
mmm... weird, I have been building for the past days, including today, with this version.... where are you getting the issue? when triggering the build of all containers together?

**Comment by bgruening** [comment]
@pcm32 I was referring to the tests. But maybe there is something else fishy?

**Comment by pcm32** [comment]
ahhh, I see what you mean now... funny that the test is sort of looking for 2.0.16 (or installing it) when we are actually pinning 2.0.15. There are some weird permission denied as well that I wouldn't expect (but then I don't do a lot of travis, so maybe is typical on that setup).

**Comment by abretaud** [comment]
The 2.0.16 install comes from the galaxy stable image I think, I made https://github.com/bgruening/docker-galaxy-stable/pull/421

**Comment by bgruening** [comment]
And green. Thanks you both. Will follow up on dev.

**Pull request merged**
