### PR TITLE
Hotfix: adds bool filters to booleans in when statements with and operators

### PR DESCRIPTION
**Pull request by pcm32**
This fixes issue #81 (explained in detail there). Simply adds `|bool` filters to boolean variables in _when_ statements when the statement has an _and_ operator between the variables.

### CODE REVIEW

**Comment by pcm32** [comment]
I see similar issues in the template files. In the startup file template, many entries get evaluated as true when in fact the boolean value is false (producing a startup with undesired entries). Adding again the `|bool` seems to work, but I presume this might be happening as well on other templates.

**Comment by bgruening** [comment]
@natefoo have you seen this one? I feel this is an ansible bug and it makes everything look so ugly. I'm fine with merging it and I'm glad @pcm32 have found it.

**Comment by pcm32** [comment]
Please bear with me, have found more things to correct related to this that should go on the same merge. Will change to WIP.

**Comment by pcm32** [comment]
Apparently this is how you should write booleans in whens, see this [issue comment](https://github.com/ansible/ansible/issues/15636#issuecomment-215286808) on ansible.

**Comment by pcm32** [comment]
Hi @bgruening I'm done with this PR, I have other improvements to add, but those will go on a separate PR. Feel free to merge this if you find it suitable, otherwise let me know. I tested all of this and seems to work fine.

**Comment by bgruening** [comment]
Tested it as well and it works as far as I can see. I would like to let someone else chime in, but if no one else respond I'm happy to merge this tomorrow.

Thanks a lot for fixing this and all your other work!

**Comment by afgane** [comment]
I've encountered this as well, way back with Ansible 1.3 even I think. We ended up doing the same (e.g., https://github.com/galaxyproject/ansible-cloudman-image/blob/master/tasks/main.yml) so I think this is just expected syntax as explained in the comment linked above.

**Comment by bgruening** [comment]
Ok! Thanks @afgane! I realised I'm just an ansible noob.

**Pull request merged**
