### PR TITLE
Update to use the latest psutil version

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by jmchilton** [comment]
We keep changing psutil, can we just make this code independent of the version we use - with a try except sort of thing?

**Comment by jmchilton** [comment]
Specifically, the file use to look like this right - 
https://github.com/galaxyproject/ansible-galaxy-extras/commit/3736c1d36f9dfa4d832f5b5fc22fbc142b090ea0

**Comment by bgruening** [comment]
@jmchilton good catch! I have fixed it. Thanks!

**Comment by jmchilton** [comment]
Awesome sauce, thanks!

**Pull request merged**
